package spock

import (
	"testing"
)

func TestExtractSequences(t *testing.T) {
	tests := []struct {
		name      string
		stmt      string
		tableInfo *TableInfo
		wantSeqs  int
		wantCols  []string
		wantTypes []string
	}{
		{
			name: "single SERIAL column",
			stmt: "CREATE TABLE users (id SERIAL PRIMARY KEY, name text)",
			tableInfo: &TableInfo{
				Schema: "public",
				Name:   "users",
			},
			wantSeqs:  1,
			wantCols:  []string{"id"},
			wantTypes: []string{"SERIAL"},
		},
		{
			name: "BIGSERIAL column",
			stmt: "CREATE TABLE events (id BIGSERIAL, data jsonb)",
			tableInfo: &TableInfo{
				Schema: "public",
				Name:   "events",
			},
			wantSeqs:  1,
			wantCols:  []string{"id"},
			wantTypes: []string{"BIGSERIAL"},
		},
		{
			name: "SMALLSERIAL column",
			stmt: "CREATE TABLE counters (id SMALLSERIAL, count int)",
			tableInfo: &TableInfo{
				Schema: "public",
				Name:   "counters",
			},
			wantSeqs:  1,
			wantCols:  []string{"id"},
			wantTypes: []string{"SMALLSERIAL"},
		},
		{
			name: "multiple SERIAL columns",
			stmt: "CREATE TABLE test (id SERIAL, other_id BIGSERIAL, name text)",
			tableInfo: &TableInfo{
				Schema: "myschema",
				Name:   "test",
			},
			wantSeqs:  2,
			wantCols:  []string{"id", "other_id"},
			wantTypes: []string{"SERIAL", "BIGSERIAL"},
		},
		{
			name: "no SERIAL columns",
			stmt: "CREATE TABLE test (id int, name text)",
			tableInfo: &TableInfo{
				Schema: "public",
				Name:   "test",
			},
			wantSeqs: 0,
		},
		{
			name:      "nil tableInfo",
			stmt:      "CREATE TABLE test (id SERIAL)",
			tableInfo: nil,
			wantSeqs:  0,
		},
		{
			name: "SERIAL with constraints",
			stmt: "CREATE TABLE test (id SERIAL NOT NULL PRIMARY KEY, name text NOT NULL)",
			tableInfo: &TableInfo{
				Schema: "public",
				Name:   "test",
			},
			wantSeqs:  1,
			wantCols:  []string{"id"},
			wantTypes: []string{"SERIAL"},
		},
		{
			name: "quoted column name with SERIAL",
			stmt: `CREATE TABLE test ("userId" SERIAL PRIMARY KEY)`,
			tableInfo: &TableInfo{
				Schema: "public",
				Name:   "test",
			},
			wantSeqs:  1,
			wantCols:  []string{"userId"},
			wantTypes: []string{"SERIAL"},
		},
		{
			name: "IDENTITY column (GENERATED ALWAYS)",
			stmt: "CREATE TABLE test (id INTEGER GENERATED ALWAYS AS IDENTITY, name text)",
			tableInfo: &TableInfo{
				Schema: "public",
				Name:   "test",
			},
			wantSeqs:  1,
			wantCols:  []string{"id"},
			wantTypes: []string{"IDENTITY"},
		},
		{
			name: "IDENTITY column (GENERATED BY DEFAULT)",
			stmt: "CREATE TABLE test (id BIGINT GENERATED BY DEFAULT AS IDENTITY)",
			tableInfo: &TableInfo{
				Schema: "public",
				Name:   "test",
			},
			wantSeqs:  1,
			wantCols:  []string{"id"},
			wantTypes: []string{"IDENTITY"},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := ExtractSequences(tt.stmt, tt.tableInfo)

			if len(got) != tt.wantSeqs {
				t.Errorf("ExtractSequences() returned %d sequences, want %d", len(got), tt.wantSeqs)
				return
			}

			for i, seq := range got {
				if i < len(tt.wantCols) && seq.Column != tt.wantCols[i] {
					t.Errorf("ExtractSequences()[%d].Column = %q, want %q", i, seq.Column, tt.wantCols[i])
				}
				if i < len(tt.wantTypes) && seq.DataType != tt.wantTypes[i] {
					t.Errorf("ExtractSequences()[%d].DataType = %q, want %q", i, seq.DataType, tt.wantTypes[i])
				}
				// Verify sequence name follows PostgreSQL convention
				if tt.tableInfo != nil && seq.Name != tt.tableInfo.Name+"_"+seq.Column+"_seq" {
					t.Errorf("ExtractSequences()[%d].Name = %q, want %q",
						i, seq.Name, tt.tableInfo.Name+"_"+seq.Column+"_seq")
				}
			}
		})
	}
}

func TestExtractColumnBody(t *testing.T) {
	tests := []struct {
		name string
		stmt string
		want string
	}{
		{
			name: "simple table",
			stmt: "CREATE TABLE test (id int, name text)",
			want: "id int, name text",
		},
		{
			name: "nested parens",
			stmt: "CREATE TABLE test (id int DEFAULT (1 + 2), name text)",
			want: "id int DEFAULT (1 + 2), name text",
		},
		{
			name: "no parens",
			stmt: "ALTER TABLE test",
			want: "",
		},
		{
			name: "complex constraints",
			stmt: "CREATE TABLE test (id int, CONSTRAINT pk PRIMARY KEY (id))",
			want: "id int, CONSTRAINT pk PRIMARY KEY (id)",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := extractColumnBody(tt.stmt)
			if got != tt.want {
				t.Errorf("extractColumnBody(%q) = %q, want %q", tt.stmt, got, tt.want)
			}
		})
	}
}

func TestGenerateSequenceAlterSQL(t *testing.T) {
	tests := []struct {
		name       string
		seq        SequenceInfo
		nodeOffset int
		want       string
	}{
		{
			name: "primary node (offset 1)",
			seq: SequenceInfo{
				Schema:    "public",
				Name:      "users_id_seq",
				Column:    "id",
				DataType:  "SERIAL",
				TableName: "users",
			},
			nodeOffset: 1,
			want:       `ALTER SEQUENCE "public"."users_id_seq" INCREMENT BY 2 RESTART WITH 1`,
		},
		{
			name: "standby node (offset 2)",
			seq: SequenceInfo{
				Schema:    "public",
				Name:      "users_id_seq",
				Column:    "id",
				DataType:  "SERIAL",
				TableName: "users",
			},
			nodeOffset: 2,
			want:       `ALTER SEQUENCE "public"."users_id_seq" INCREMENT BY 2 RESTART WITH 2`,
		},
		{
			name: "custom schema",
			seq: SequenceInfo{
				Schema:    "myschema",
				Name:      "events_id_seq",
				Column:    "id",
				DataType:  "BIGSERIAL",
				TableName: "events",
			},
			nodeOffset: 1,
			want:       `ALTER SEQUENCE "myschema"."events_id_seq" INCREMENT BY 2 RESTART WITH 1`,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := GenerateSequenceAlterSQL(tt.seq, tt.nodeOffset)
			if got != tt.want {
				t.Errorf("GenerateSequenceAlterSQL() = %q, want %q", got, tt.want)
			}
		})
	}
}

func TestGenerateAllSequenceAlters(t *testing.T) {
	tests := []struct {
		name       string
		tableInfo  *TableInfo
		nodeOffset int
		wantCount  int
	}{
		{
			name: "table with sequences",
			tableInfo: &TableInfo{
				Schema: "public",
				Name:   "users",
				Sequences: []SequenceInfo{
					{Schema: "public", Name: "users_id_seq", Column: "id"},
					{Schema: "public", Name: "users_other_seq", Column: "other"},
				},
			},
			nodeOffset: 1,
			wantCount:  2,
		},
		{
			name: "table without sequences",
			tableInfo: &TableInfo{
				Schema:    "public",
				Name:      "users",
				Sequences: nil,
			},
			nodeOffset: 1,
			wantCount:  0,
		},
		{
			name:       "nil tableInfo",
			tableInfo:  nil,
			nodeOffset: 1,
			wantCount:  0,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := GenerateAllSequenceAlters(tt.tableInfo, tt.nodeOffset)
			if len(got) != tt.wantCount {
				t.Errorf("GenerateAllSequenceAlters() returned %d alters, want %d", len(got), tt.wantCount)
			}
		})
	}
}

func TestWrapSequenceAlterDDL(t *testing.T) {
	alterSQL := `ALTER SEQUENCE "public"."users_id_seq" INCREMENT BY 2 RESTART WITH 1`
	repSets := []string{"default", "ddl_sql"}

	result := WrapSequenceAlterDDL(alterSQL, repSets)

	// Should be wrapped with spock.replicate_ddl
	if result == alterSQL {
		t.Error("WrapSequenceAlterDDL() should wrap the SQL")
	}

	// Should contain the original SQL
	if !contains(result, alterSQL) {
		t.Errorf("WrapSequenceAlterDDL() should contain original SQL, got: %s", result)
	}

	// Should use $spock_ddl$ tags
	if !contains(result, "$spock_ddl$") {
		t.Errorf("WrapSequenceAlterDDL() should use $spock_ddl$ tags, got: %s", result)
	}
}

func contains(s, substr string) bool {
	return len(s) >= len(substr) && (s == substr || len(s) > 0 && containsHelper(s, substr))
}

func containsHelper(s, substr string) bool {
	for i := 0; i <= len(s)-len(substr); i++ {
		if s[i:i+len(substr)] == substr {
			return true
		}
	}
	return false
}
